---
name: credhub-webui

releases:
- name: credhub-webui
  version: 0.0.3
  sha1: 566e3c845b00a409c64f5a99182d58ac23c7df41
  url: https://github.com/shreddedbacon/credhub-webui-boshrelease/releases/download/v0.0.3/credhub-webui-boshrelease-0.0.3.tgz

stemcells:
- os: ubuntu-trusty
  alias: default
  version: latest

instance_groups:
- name: web
  instances: 1
  stemcell: default
  azs: [z1]
  vm_type: default
  persistent_disk_type: default
  networks:
  - name: default
  jobs:
  - name: credhub-webui
    release: credhub-webui
    properties:
      credhub_server: "((credhub_server))"
      ui_url: "https://((credhub_webui_hostname)):8443"
      client_id: ((credhub_client_id))
      client_secret: ((credhub_client_secret))
      ssl:
        certificate: ((credhub_webui_tls.certificate))
        key: ((credhub_webui_tls.private_key))

variables:
- name: credhub_webui_tls
  type: certificate
  options:
    self_sign: true
    common_name: ((credhub_webui_hostname))
    alternative_names: [localhost]

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
